name: message_wise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  file_picker: ^5.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.7
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  line_icons: ^2.0.3
  rxdart: ^0.27.7
  sticky_headers: ^0.3.0+2
  top_snackbar_flutter: ^3.1.0
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
